// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3n3s-taUhX8bPsNR6V_qQHJe8BUTunX8',
    appId: '1:942913166251:web:bd2f37309e9bfb5041d0ee',
    messagingSenderId: '942913166251',
    projectId: 'egyptian-excursion-uk',
    authDomain: 'egyptian-excursion-uk.firebaseapp.com',
    databaseURL: 'https://egyptian-excursion-uk-default-rtdb.firebaseio.com',
    storageBucket: 'egyptian-excursion-uk.appspot.com',
    measurementId: 'G-NGLWT4T607',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJpcAIDfmJN0ka73m4vlkVR-wYEkSX0E',
    appId: '1:942913166251:android:fe77ad1eebf4156841d0ee',
    messagingSenderId: '942913166251',
    projectId: 'egyptian-excursion-uk',
    databaseURL: 'https://egyptian-excursion-uk-default-rtdb.firebaseio.com',
    storageBucket: 'egyptian-excursion-uk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTVt0fhz-2CylvcJ_DfMx_hMU-EAqcklk',
    appId: '1:942913166251:ios:4da4d65b70022e2d41d0ee',
    messagingSenderId: '942913166251',
    projectId: 'egyptian-excursion-uk',
    databaseURL: 'https://egyptian-excursion-uk-default-rtdb.firebaseio.com',
    storageBucket: 'egyptian-excursion-uk.appspot.com',
    androidClientId: '942913166251-o62lrqiucrpitir04muioqn84l2abqma.apps.googleusercontent.com',
    iosClientId: '942913166251-35frtnqkcbv58acvpsqsnbogijoi0lkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTVt0fhz-2CylvcJ_DfMx_hMU-EAqcklk',
    appId: '1:942913166251:ios:4da4d65b70022e2d41d0ee',
    messagingSenderId: '942913166251',
    projectId: 'egyptian-excursion-uk',
    databaseURL: 'https://egyptian-excursion-uk-default-rtdb.firebaseio.com',
    storageBucket: 'egyptian-excursion-uk.appspot.com',
    androidClientId: '942913166251-o62lrqiucrpitir04muioqn84l2abqma.apps.googleusercontent.com',
    iosClientId: '942913166251-35frtnqkcbv58acvpsqsnbogijoi0lkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
